GET http://localhost:3000/carts

###

GET http://localhost:3000/carts/2

###

GET http://localhost:3000/carts/2/cartItens

###

DELETE http://localhost:3000/carts/1/cartItens

###

POST http://localhost:3000/carts
Content-Type: application/json

{
    "userId": 5,
    "status": "aberto"
}

###
POST http://localhost:3000/cartItens
Content-Type: application/json

{
    "cartId": 1,
    "productId": 1,
    "quantity": 8
}

###

PUT http://localhost:3000/carts/2
Content-Type: application/json

{
    "status": "encerrado"
}

###

DELETE http://localhost:3000/carts/2