POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "luka",
    "email": "dontit@mail.com",
    "senha": "000",
    "foto": "aaaa",
    "id_turma": 3,
    "id_escola": 1,
    "matricula":"900990",
    "experiencia": 0,
    "tipo_usuario_id": 2,
    "nivel": 12,
     "genero":"M"
}

###

GET http://localhost:3000/usuarios

###

GET http://localhost:3000/usuarios/2

###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "João da Silva"
}

###

DELETE http://localhost:3000/usuarios/5